name       = "datablitz-api"
main       = "frontend/worker.js"
compatibility_date = "2024-11-01"

# KV namespace — create with: wrangler kv:namespace create "DATABLITZ_KV"
# Then paste the id below
[[kv_namespaces]]
binding = "DATABLITZ_KV"
id      = "517788ccef6d4a15af8267f0d926950a"

[vars]
ENVIRONMENT = "production"
