"""
datablitz.delivery.formatter
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Converts the AI narrative JSON into Markdown and HTML
ready for static site generation and email delivery.
"""

from __future__ import annotations

import json
import re
from datetime import datetime
from pathlib import Path


def load_narrative(path: str) -> dict:
    return json.loads(Path(path).read_text())


def narrative_to_markdown(narrative: dict) -> str:
    """
    Convert narrative JSON to clean Markdown for the static site.
    """
    run_date = datetime.fromisoformat(
        narrative["generated_at"].replace("Z", "+00:00")
    ).strftime("%B %d, %Y")

    meta = narrative.get("meta", {})
    countries = ", ".join(c.upper() for c in meta.get("countries", []))

    lines = [
        f"# DataBlitz Weekly Digest",
        f"**{run_date}** | Covering: {countries} | "
        f"{meta.get('indicators_total', '?')} live indicators\n",
        "---\n",
        narrative["main_narrative"],
        "\n---\n",
        "## Country Snapshots\n",
    ]

    for country, brief in narrative.get("country_briefs", {}).items():
        lines.append(f"### {country.upper()}\n")
        lines.append(brief)
        lines.append("")

    lines += [
        "\n---",
        f"*Generated by DataBlitz AI engine on {run_date}. "
        f"Data sourced from open government APIs: FRED, ONS, BCB, IBGE, World Bank, OpenAQ, and others.*",
    ]

    return "\n".join(lines)


def narrative_to_email_html(narrative: dict) -> str:
    """
    Convert narrative to a clean HTML email body.
    Uses inline styles — no external CSS (email client compatibility).
    """
    run_date = datetime.fromisoformat(
        narrative["generated_at"].replace("Z", "+00:00")
    ).strftime("%B %d, %Y")

    main = narrative["main_narrative"]

    # Parse sections from the main narrative markdown
    sections = _parse_sections(main)
    headline = sections.get("HEADLINE", "This week in global data").strip()

    html_parts = [
        f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>DataBlitz — {run_date}</title></head>
<body style="font-family: Georgia, serif; max-width: 680px; margin: 0 auto; padding: 24px; color: #1a1a1a; background: #fff;">

<div style="border-bottom: 3px solid #1a1a1a; padding-bottom: 16px; margin-bottom: 24px;">
  <p style="font-size: 11px; letter-spacing: 0.1em; text-transform: uppercase; color: #666; margin: 0 0 8px;">DataBlitz Weekly</p>
  <h1 style="font-size: 28px; margin: 0 0 8px; line-height: 1.2;">{headline}</h1>
  <p style="font-size: 13px; color: #888; margin: 0;">{run_date}</p>
</div>"""]

    # Big Three
    big_three = sections.get("THE BIG THREE", "")
    if big_three:
        html_parts.append(
            f'<h2 style="font-size: 18px; border-bottom: 1px solid #eee; padding-bottom: 8px;">The Big Three</h2>'
        )
        html_parts.append(_md_to_html(big_three))

    # Cross-country signal
    signal = sections.get("CROSS-COUNTRY SIGNAL", "")
    if signal:
        html_parts.append(
            f"""<div style="background: #f8f8f0; border-left: 4px solid #1a1a1a; padding: 16px 20px; margin: 24px 0;">
  <p style="font-size: 11px; text-transform: uppercase; letter-spacing: 0.08em; margin: 0 0 8px; color: #666;">Cross-Country Signal</p>
  {_md_to_html(signal)}
</div>"""
        )

    # Numbers of the week
    numbers = sections.get("NUMBERS OF THE WEEK", "")
    if numbers:
        html_parts.append(
            '<h2 style="font-size: 18px; border-bottom: 1px solid #eee; padding-bottom: 8px;">Numbers of the Week</h2>'
        )
        html_parts.append(_md_to_html(numbers))

    # Data watch
    watch = sections.get("DATA WATCH", "")
    if watch:
        html_parts.append(
            '<h2 style="font-size: 18px; border-bottom: 1px solid #eee; padding-bottom: 8px;">Data Watch</h2>'
        )
        html_parts.append(_md_to_html(watch))

    # Footer
    html_parts.append(f"""
<div style="border-top: 1px solid #eee; margin-top: 32px; padding-top: 16px; font-size: 11px; color: #999;">
  <p>DataBlitz — AI-powered global data digest. Sources: FRED, ONS, BCB, IBGE, World Bank, OpenAQ &amp; more.</p>
  <p>Run ID: {narrative.get('run_id', '?')}</p>
</div>
</body>
</html>""")

    return "\n".join(html_parts)


def _parse_sections(text: str) -> dict[str, str]:
    """Split markdown by ## headings into a dict."""
    sections: dict[str, str] = {}
    current_key: str | None = None
    current_lines: list[str] = []

    for line in text.splitlines():
        heading = re.match(r"^## (.+)$", line)
        if heading:
            if current_key:
                sections[current_key] = "\n".join(current_lines).strip()
            current_key = heading.group(1).strip()
            current_lines = []
        else:
            if current_key is not None:
                current_lines.append(line)

    if current_key:
        sections[current_key] = "\n".join(current_lines).strip()

    return sections


def _md_to_html(text: str) -> str:
    """Minimal Markdown → HTML (bold, paragraphs, bullets). No external deps."""
    lines = text.splitlines()
    html_lines = []
    in_list = False

    for line in lines:
        stripped = line.strip()
        if not stripped:
            if in_list:
                html_lines.append("</ul>")
                in_list = False
            html_lines.append("")
            continue

        # Bullet point
        if stripped.startswith("- ") or stripped.startswith("• "):
            if not in_list:
                html_lines.append('<ul style="padding-left: 20px; margin: 12px 0;">')
                in_list = True
            content = _inline_md(stripped[2:])
            html_lines.append(f'  <li style="margin: 6px 0; line-height: 1.6;">{content}</li>')
        else:
            if in_list:
                html_lines.append("</ul>")
                in_list = False
            content = _inline_md(stripped)
            html_lines.append(f'<p style="line-height: 1.7; margin: 12px 0;">{content}</p>')

    if in_list:
        html_lines.append("</ul>")

    return "\n".join(html_lines)


def _inline_md(text: str) -> str:
    """Convert inline **bold** markdown to HTML."""
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"\*(.+?)\*", r"<em>\1</em>", text)
    return text
